version: '3.3'

services:

  sites:
    build:
      context: ./services/sites
      dockerfile: Dockerfile-dev
    volumes:
      - './services/sites:/usr/src/app'
    ports:
      - 5001:5000
    environment:
      - FLASK_ENV=development
      - APP_SETTINGS=project.config.DevelopmentConfig
      - DATABASE_URL=postgres://postgres:postgres@sites-db:5432/sites_dev  # new
      - DATABASE_TEST_URL=postgres://postgres:postgres@sites-db:5432/sites_test  # new
    depends_on:  # new
      - sites-db

  client:
    build:
      context: ./services/client
      dockerfile: Dockerfile-dev
    volumes:
      - './services/client:/usr/src/app'
      - '/usr/src/app/node_modules'
    ports:
      - 3007:3000
    environment:
      - NODE_ENV=development
      - REACT_APP_SITES_SERVICE_URL=${REACT_APP_SITES_SERVICE_URL}
    depends_on:
      - sites

  sites-db:  # new
    build:
      context: ./services/sites/project/db
      dockerfile: Dockerfile
    ports:
      - 5435:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    
  nginx:
    build:
      context: ./services/nginx
      dockerfile: Dockerfile-dev
    restart: always
    ports:
      - 88:88
    depends_on:
      - sites
      - client
