# base image
FROM python:3.6.5-alpine

# new
# install dependencies
RUN apk update && apk upgrade

RUN apk add --virtual .pynacl_deps build-base python3-dev libffi-dev 

RUN apk add postgresql-dev && \
    apk add netcat-openbsd

# set working directory
WORKDIR /usr/src/app

# add and install requirements
COPY ./requirements.txt /usr/src/app/requirements.txt
RUN python -m pip install --upgrade pip setuptools wheel
#RUN pip install --upgrade pip
RUN pip install -r requirements.txt

# new
# add entrypoint.sh
COPY ./entrypoint.sh /usr/src/app/entrypoint.sh
RUN chmod +x /usr/src/app/entrypoint.sh

# add app
COPY . /usr/src/app

# new
# run server
CMD ["/usr/src/app/entrypoint.sh"]
